language: ruby

bundler_args: --without tools

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-19mode
  - rbx-2

env:
  matrix:
    - HANDLER="nokogiri"
    - HANDLER="ox"
    - HANDLER="oga"

matrix:
  allow_failures:
    - env: HANDLER="ox"
      rvm: jruby-19mode
